### PR TITLE
Update FAQ: Why don't I see my domain?

### LINKED ISSUE #274: get.gov: Update content for when users don't see their domain
### Issue description
As a domain manager, I want to understand why I don't see my domains when I sign into the registrar so I can make sure my account is correctly linked. 

We will be adding a link to the domains table on the dashboard if the domains table is empty in issue cisagov/manage.get.gov#2056 . That link will point to help content at https://get.gov/help/faq/#do-not-see-my-domain. The content linked here is helpful for legacy users mainly, however, other users who have simply linked the wrong login.gov account to .gov could use content to help them self serve

### Acceptance criteria

- [x] Content is added to [google doc](https://docs.google.com/document/d/1bfBndWQzSJLzx2WOLKiaLRVmSsl6mxbYzBxBU7R1848/edit#heading=h.zi5izuhjwriu)
- [x] Updates made at get.gov

### Links to other issues
Relates to cisagov/manage.get.gov#2056

### PR DESCRIPTION
**Pull request by Katherine-Osos**
## Ticket

Resolves #274 

### Changes 
Updated content within the [FAQ](https://get.gov/help/faq/#do-not-see-my-domain) for this question: Why don’t I see my domain when I sign in to the registrar?

Updates should match text in [this Google Doc](https://docs.google.com/document/d/1bfBndWQzSJLzx2WOLKiaLRVmSsl6mxbYzBxBU7R1848/edit#heading=h.zi5izuhjwriu).

### Review updates
You can review the updates at this [link](https://federalist-877ab29f-16f6-4f12-961c-96cf064cf070.sites.pages.cloud.gov/preview/cisagov/get.gov/ko/faq-dont-see-domain/help/faq/).

### CODE REVIEW

**Review by rileyorr — APPROVED** [review]
This LGTM - great job! The updated content matches the Google Doc and the links work correctly. 

The only thing I'll mention as food for thought is that I noticed some of the links open in a new tab while others don't. W3C recommends opening new windows and tabs from a link only when necessary since it can be disorienting for users and difficult to navigate back to the previous page ([source](https://www.w3.org/TR/WCAG20-TECHS/G200.html)). I think in this case it's likely fine since we're linking to a page that requires authentication, Login.gov, but we might consider notifying users that the link will open in a new tab.

**Review by h-m-f-t — APPROVED** [review]
🎉

**Comment by Katherine-Osos** [comment]
@rileyorr That's a great callout! Right now on get.gov, I think only "sign in" links open in a new tab, and all others open in the same tab. So I followed that pattern for consistency. But do you mind creating a ticket to come up with a better linking strategy that aligns with accessibility best practices?

**Comment by rileyorr** [comment]
Those are great points, thank you! I did some digging in the Google Drive and discovered we have [a .gov content style guide with a section about links ](https://docs.google.com/document/d/1U-TRx3ecCFZ-qtrCk7EYmF_nmfKh6kd7FV95Pa4iWeM/edit#heading=h.uu1tgvdl81ni). If this is an actively used document I think it makes sense to have a ticket to update the linking guidelines in that document. Since the accessibility plan is a source of truth of how accessibility is incorporated into the design and development process I'd suggest we include a content section that links to that content style guide, especially since there's also a section in that document about plain language guidelines. Let me know what y'all think!

**Comment by h-m-f-t** [comment]
Sounds great to me, @rileyorr! I defer to @Katherine-Osos.

**Comment by Katherine-Osos** [comment]
Agreed - go ahead and create a new ticket, @rileyorr. And thanks for connecting all the pieces!

**Comment by rileyorr** [comment]
Thank you both! I've created the ticket here: https://github.com/cisagov/manage.get.gov/issues/2107

**Pull request merged**
