### PR TITLE
#303 - Implement answers to contact form

### LINKED ISSUE #303: Implement answers to contact form
### Issue description

In https://github.com/cisagov/get.gov/issues/288, we experimented with modifying the Contact Us form to guide users to the right answers so (perhaps) they don't need to submit the form at all. In https://github.com/cisagov/get.gov/issues/289, we tested out the viability of updating the form with a prototype. In #300, we finalized the content updates. Now, let's implement the changes!

### Acceptance criteria

- [x] Reformat the contact form prototype with updates from the [content doc](https://docs.google.com/document/d/1kmw4HHacwl_sHyPvNmInRrFzguCaT-F60t_qX-ki7kI/edit) 
- [x] Test out prototype with existing contact form submissions (acting as the past submitter, would you have been able to find answers and/or reach out at the end using the new form?)
   - [ ] reach out to Cameron for some examples
- [ ] Test out accessibility (Microsoft Forms has accessibility issues, particularly with tabbing through multiple choice options. Accessibility issues will not be addressed in this ticket, but should take note)
- [x] Share prototype with team for final feedback
- [ ] Replace existing contact form with prototype
- [ ] See how new contact work affects helpdesk volume, address any potential issues that come up a week after implementation

### Additional context

Link to [Google doc](https://docs.google.com/document/d/1kmw4HHacwl_sHyPvNmInRrFzguCaT-F60t_qX-ki7kI/edit)
Link to [prototype](https://forms.office.com/Pages/ResponsePage.aspx?id=bOfNPG2UEkq7evydCEI1SqHke9Gh6wJEl3kQ5EjWUKlURE04OUo3WTYyUEhIVENXSFlGNU01WjVaNy4u)

### Links to other issues

Steps for updating the form: 
1. #288 
2. #289 
3. #300 
4. #303 (📍 YOU ARE HERE)

Note; This effort will update the Microsoft Form, but will not replace it. We will work on replacing the contact form with our own customized solution in [#2011](https://github.com/cisagov/manage.get.gov/issues/2011) and [#2099](https://github.com/cisagov/manage.get.gov/issues/2099)

### PR DESCRIPTION
**Pull request by kristinacyin**
## Ticket

Resolves #303

## Changes

For the sake of creating a PR, I updated the iframe embed link from the old contact form to the new (prototype) one. Note that before we can actually carry through with the change the following items need to be completed:
- [x] Remove "[PROTOTYPE]" in title
- [x] Change settings to allow responses from anyone
- [x] Use PowerAutomate to set up processes
    - [x] Forward responses to help desk inbox
    - [x] Move "Does the information provided answer your question - Yes" emails to a separate folder so they don't clutter inbox
    - [x] Remove "FAKE" from emails that get sent to help@get.gov
- [x] Delete test responses
- [ ] Establish method of tracking / acquire metrics for
    - [ ] Avg. number of emails sent to helpdesk **before** new contact form is implemented
    - [ ] Avg. number of emails sent to helpdesk **after** new contact form is implemented

## Context for reviewers

Old contact form is currently embedded on [get.gov/contact](https://get.gov/contact/) 
[Prototype form](https://forms.office.com/Pages/ResponsePage.aspx?id=bOfNPG2UEkq7evydCEI1SseS7Uruj0hGoPWlATpAlzVURTdIVDZWVE01TTJTSlZJOEJVM0tPOFcxSS4u) (set to only allow responses from DHS for now) 
[Prototype form content doc](https://docs.google.com/document/d/1kmw4HHacwl_sHyPvNmInRrFzguCaT-F60t_qX-ki7kI/edit?usp=sharing)
[Preview of what the prototype form will look like on get.gov](https://federalist-877ab29f-16f6-4f12-961c-96cf064cf070.sites.pages.cloud.gov/preview/cisagov/get.gov/ky/contact-form/contact/)

### Reviewers, please check the following
- There is consistency between content doc and prototype form
- The branching and form logic make sense
- Required questions are required, optional questions are optional (and have the "(optional)" text appended to the question text) 
- Please note any accessibility issues in the [content doc](https://docs.google.com/document/d/1kmw4HHacwl_sHyPvNmInRrFzguCaT-F60t_qX-ki7kI/edit#bookmark=id.j2isrqkru5gn) for future reference
- If you find any typos, grammatical issues, etc., please comment in the [content doc](https://docs.google.com/document/d/1kmw4HHacwl_sHyPvNmInRrFzguCaT-F60t_qX-ki7kI/edit?usp=sharing) (easier for me to reference there)

### CODE REVIEW

**Comment by kristinacyin** [comment]
@h-m-f-t Tagging you here in case you would like to look at it too, and I would like to go over how to set up Power Automate automations for the form (and ways we can track metrics in the inbox) once we're ready to transition to the new form

**Comment by h-m-f-t** [comment]
Nice! @kristinacyin:
* Can you review the last few weeks of commits to this repo for changes relevant text? e.g., ce5536d
* Can you share permissions over the actual form with me?

**Comment by kristinacyin** [comment]
@h-m-f-t 

> Nice! @kristinacyin:
> 
> * Can you review the last few weeks of commits to this repo for changes relevant text? e.g., [ce5536d](https://github.com/cisagov/get.gov/commit/ce5536d0d03516bdddece2a7275c1715c5cff3ae)
> * Can you share permissions over the actual form with me?

Reviewed all the new edits to the help content and didn't notice any discrepancies. There's new content about user profiles, but I'm not sure I want to add that to the contact form yet until someone actually submits a question about it.

Also I added you as a collaborator to the form! I want to transfer ownership of the form to you as well, and I'm figuring out the best way to do so.

**Review by katypies — COMMENTED** [review]
This looks great to me. Clicked through to view all the content, and I agree with not changing anything with respect to the contact info/User Profile at this time. Seems like we could add additional branches or logic, should there be a lot of questions about other topics we haven't covered here!

**Review by witha-c — APPROVED** [review]
Read through the content doc and clicked through all the branches in the form to compare. Looks great! Nice work!

**Pull request merged**
